# Generated by Django 5.2.6 on 2025-09-25 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.ImageField(upload_to='uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_seed_image', models.BooleanField(default=False)),
                ('features_extracted', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField()),
                ('extraction_model', models.CharField(default='resnet50', max_length=50)),
                ('vector_size', models.PositiveIntegerField(default=2048)),
                ('extraction_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='images.image')),
            ],
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['features_extracted'], name='images_imag_feature_b6b93b_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_seed_image'], name='images_imag_is_seed_aee544_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_hash'], name='images_imag_image_h_74bbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='imagefeature',
            index=models.Index(fields=['extraction_model'], name='images_imag_extract_be2de3_idx'),
        ),
        migrations.AddIndex(
            model_name='imagefeature',
            index=models.Index(fields=['created_at'], name='images_imag_created_8cb77b_idx'),
        ),
    ]
