# Generated by Django 5.2.6 on 2025-09-25 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_threshold', models.FloatField(default=0.7)),
                ('max_results', models.PositiveIntegerField(default=20)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('search_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchquery')),
                ('similar_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_results', to='images.image')),
            ],
            options={
                'ordering': ['search_query', 'rank'],
                'indexes': [models.Index(fields=['similarity_score'], name='search_simi_similar_3b57d9_idx'), models.Index(fields=['rank'], name='search_simi_rank_610343_idx')],
                'unique_together': {('search_query', 'similar_image')},
            },
        ),
    ]
